script: 'ci/travis.rb'
rvm:
  - ruby-head
  - 2.2
  - 2.1
  - 2.0
  - jruby-head
  - rbx-2
gemfile:
  - Gemfile
notifications:
  email:
    recipients:
      - Martin.Bosslet@gmail.com
    on_success: always
    on_failure: always
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: ruby-head
